config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :objets
  resources :articles
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/home'
  get 'pages/contact'
  get 'pages/about'
  root 'pages#home'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/objet.rb
class Objet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  access all: [:show, :index], user: {except: [:destroy]}, admin: :all

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to root_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    access all: [:show, :index], user: {except: [:destroy]}, admin: :all

    #GET /books
    #GET /books.json
    def index
        @books = Book.all
    end

    #GET /books/1
    #GET /books/1.json
    def show
    end

    #GET /books/new
    def new 
        @book = Book.new
    end

    #GET /books/1/edit
    def edit
    end

    # POST /books
    # POST /books.json
    def create
        @book = Book.new(book_params)

        respond_to do |format|
            if @book.save
                format.html { redirect_to root_path, notice: 'book was successfully created.'}
                format.json { render :show, status: :created, location: @book }
            else 
                format.html { render :new}
                format.json { render json: @book.errors, status: :unprocessable_entity}
            end
        end
    end

    # PATCH/PUT /books/1
    # PATCH/PUT /books/1.json
    def update
        respond_to do |format|
            if @book.update(book_params)
                format.html { redirect_to root_path, notice: 'book was successfully update.'}
                format.json { render :show, status: :ok, location: @book }
            else
                format.html { render :edit}
                format.json { render json: @book.errors, status: :unprocessable_entity}
            end
        end
    end

    # DELETE /books/1
    # DELETE /books/1.json
    def destroy
        @book.destroy
        respond_to do |format|
            format.html { redirect_to root_path, notice: 'book was successfully destroyed.'}
            format.json { head :no_content }
        end
    end

    private

    def set_book 
        @book = Book.find(params[:id])
    end

    def book_params
        params.require(:book).permit(:title, :content)
    end


end

app/controllers/objets_controller.rb
class ObjetsController < ApplicationController
  before_action :set_objet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  access all: [:show, :index], user: {except: [:destroy]}, admin: :all

  # GET /objets
  # GET /objets.json
  def index
    @objets = Objet.all
  end

  # GET /objets/1
  # GET /objets/1.json
  def show
  end

  # GET /objets/new
  def new
    @objet = Objet.new
  end

  # GET /objets/1/edit
  def edit
  end

  # POST /objets
  # POST /objets.json
  def create
    @objet = Objet.new(objet_params)

    respond_to do |format|
      if @objet.save
        format.html { redirect_to root_path, notice: 'Objet was successfully created.' }
        format.json { render :show, status: :created, location: @objet }
      else
        format.html { render :new }
        format.json { render json: @objet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objets/1
  # PATCH/PUT /objets/1.json
  def update
    respond_to do |format|
      if @objet.update(objet_params)
        format.html { redirect_to root_path, notice: 'Objet was successfully updated.' }
        format.json { render :show, status: :ok, location: @objet }
      else
        format.html { render :edit }
        format.json { render json: @objet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objets/1
  # DELETE /objets/1.json
  def destroy
    @objet.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Objet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objet
      @objet = Objet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objet_params
      params.require(:objet).permit(:title, :content, :price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
        @articles = Article.all
        @objets = Objet.all 
        @books = Book.all 
    end

    def contact
    end

    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/objets_helper.rb
module ObjetsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>
</br>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(objet.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.content %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New book', new_book_path %>
</br>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @book.content %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rooting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render  "partials/nav" %>

    <%= yield %>
  </body>
</html>

app/views/objets/_form.html.erb
<%= form_with(model: objet, local: true) do |form| %>
  <% if objet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(objet.errors.count, "error") %> prohibited this objet from being saved:</h2>

      <ul>
      <% objet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/objets/edit.html.erb
<h1>Editing Objet</h1>

<%= render 'form', objet: @objet %>

<%= link_to 'Show', @objet %> |
<%= link_to 'Back', objets_path %>

app/views/objets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Objets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @objets.each do |objet| %>
      <tr>
        <td><%= objet.title %></td>
        <td><%= objet.content %></td>
        <td><%= objet.price %></td>
        <td><%= link_to 'Show', objet %></td>
        <td><%= link_to 'Edit', edit_objet_path(objet) %></td>
        <td><%= link_to 'Destroy', objet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Objet', new_objet_path %>

app/views/objets/new.html.erb
<h1>New Objet</h1>

<%= render 'form', objet: @objet %>

<%= link_to 'Back', objets_path %>

app/views/objets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @objet.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @objet.content %>
</p>

<p>
  <strong>Price:</strong>
  <%= @objet.price %>
</p>

<%= link_to 'Edit', edit_objet_path(@objet) %> |
<%= link_to 'Back', objets_path %>

app/views/pages/_list_articles.html.erb
</br>
<% if logged_in?(:admin) %>
<h1 class="title has-text-danger">Articles</h1>
<% else %>
<h1 class="title ">Articles</h1>
<% end %>
<% @articles.each do |article| %>
</br>
<%= link_to article.title,article %>
</br>
<%= article.content %>
</br>
<%= link_to "editer #{article.title}", edit_article_path(article), data: {confirm:'are you sure ?'}%>
</br>
<%= link_to "destroy #{article.title}", article, method: :delete, data: {confirm:"are you sure?"}%>
</br>
<% end %>
</br>

app/views/pages/_list_books.html.erb
</br>
<% if logged_in?(:admin) %>
<h1 class="title has-text-danger">Books</h1>
<% else %>
<h1 class="title">Books</h1>
<% end %>
<% @books.each do |book| %>
</br>
<%= link_to book.title,book %>
</br>
<%= book.content %>
</br>
<%= link_to "editer #{book.title}", edit_book_path(book)%>
</br>
<%= link_to "destroy #{book.title}", book, method: :delete, data: {confirm:"are you sure?"}%>
</br>
<% end %>
</br>

app/views/pages/_list_objets.html.erb
<% if logged_in?(:admin) %>
<h1 class="title has-text-danger">Objets</h1>
<% else  %>
<h1 class="title">Objets</h1>
<% end %>
<% @objets.each do |objet| %>
</br>
<%= link_to objet.title,objet %>
</br>
<%= objet.content %>
</br>
<%= objet.price %>
</br>
<%= link_to "editer", edit_objet_path(objet) if logged_in?(:admin, :user) %>
</br>
<%= link_to "destroy", objet, method: :delete, data: {confirm:"are you sure?"} if logged_in?(:admin) %>
</br>

<% end %>

app/views/pages/about.html.erb
<h1>A propos</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/home.html.erb
<%= render 'list_articles'%>

<%= render 'list_objets'%>

<%= render 'list_books'%>

app/views/partials/_links.html.erb
<%= link_to 'accueil', root_path %>
    <%= link_to 'contact', pages_contact_path %>
    <%= link_to 'about', pages_about_path %>
    <%= link_to 'article', articles_path %>
    <%= link_to 'New article', new_article_path %>
    <p>/.../</p>
    <%= link_to 'accueil objet', objets_path %>
    <%= link_to 'New objet', new_objet_path %>
    <p> / .../</p>
    
    <%= link_to 'accueil book', books_path %>
    <%= link_to 'New objet', new_book_path %>

app/views/partials/_nav.html.erb
<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if logged_in?(:admin) %>
  <nav class="navbar is-danger" role="navigation" aria-label="main navigation">
  <% else %>
  <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <% end %>
  <div class="navbar-brand">
  
  <%= link_to root_path, class: "navbar-item" do %>
    <h1 class="title is-5">Test routes</h1>
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        <%= render 'partials/links' %>
      </a>  
    </div>


    <div class="navbar-end">

      <div class="navbar-item">

        <div class="buttons">


          <% if user_signed_in? %>
          <p class="control"><%= link_to 'Se déconnecter ', destroy_user_session_path, method: :delete, class: 'button is-black' %></p>
          <p class="control"><%= link_to "Editer #{current_user.email}", edit_user_registration_path, class: 'button is-black' %></p>
          <% else %>
          <p class="control"><%= link_to 'Se connecter', new_user_session_path, class: 'button is-black'  %></p>
          <p class="control"><%= link_to "S'inscrire", new_user_registration_path, class: "button is-black"  %></p>     
          <% end %>
        
        
        </div>
      </div>
    </div>
  </div>
</nav>